name: siris_next_gen
version: 0.0.1
environment:
  sdk: ">=1.4.2"
dependencies:
  angular: '>=0.12.0 <0.13.0'
  browser: ">=0.10.0+2 <0.11.0"
  di: ">= 0.0.40"
  observe: any
  polymer: any
  shadow_dom: any
dev_dependencies:
  unittest: any
  dart_to_js_script_rewriter: ">=0.0.1+2 <0.1.0"
  sass: ">=0.3.0 <0.4.0"
transformers:
- dart_to_js_script_rewriter
- [angular, sass]
